name: API Tests (Newman)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run Newman tests
        run: |
          npx newman run postman/collection.json \
            -r cli,html \
            --reporter-html-export reports/report-$(date +%Y-%m-%d).html

      - name: Upload HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: reports/